services:
  wp_jennythebaker-com:
    image: wordpress:fpm-alpine
    restart: always
    networks:
      - reverse-proxy
      - jennythebaker-com
    depends_on:
      - mariadb_jennythebaker-com
      - redis_jennythebaker-com
    volumes:
      - jennythebaker-com_files:/var/www/html

  redis_jennythebaker-com:
    image: redis:32bit
    restart: always
    networks:
      - jennythebaker-com
    depends_on:
      - mariadb_jennythebaker-com
    volumes:
      - jennythebaker-com_cache:/data
    command: ["redis-server", "--appendonly", "yes"]

  mariadb_jennythebaker-com:
    image: mariadb:lts
    restart: always
    networks:
      - jennythebaker-com
    volumes:
      - jennythebaker-com_data:/var/lib/mysql

  wp-cli_jennythebaker-com:
    image: wordpress:cli
    networks:
      - jennythebaker-com
    volumes:
      - jennythebaker-com_files:/var/www/html

networks:
  reverse-proxy:
    name: wp-host_reverse-proxy
    external: true
  jennythebaker-com:

volumes:
  jennythebaker-com_files:
  jennythebaker-com_cache:
  jennythebaker-com_data: